version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "Enhancement"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/Libraries/AMD64"
    labels:
      - "Enhancement"
      - "Project:AMD64"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/SkyLift"
    labels:
      - "Enhancement"
      - "Project:SkyLift"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/Sky"
    labels:
      - "Enhancement"
      - "Project:Sky"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/Libraries/SkyBuffer"
    labels:
      - "Enhancement"
      - "Project:SkyBuffer"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/Libraries/SkyLiftKit"
    labels:
      - "Enhancement"
      - "Project:SkyLiftKit"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/Extensions/SKTest"
    labels:
      - "Enhancement"
      - "Project:SKTest"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/Extensions/PCIKit"
    labels:
      - "Enhancement"
      - "Project:PCIKit"
    schedule:
      interval: "daily"
