version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "Enhancement"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/Libraries/AMD64"
    labels:
      - "Enhancement"
      - "Project:AMD64"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/XBoot"
    labels:
      - "Enhancement"
      - "Project:XBoot"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/Kernel"
    labels:
      - "Enhancement"
      - "Project:Kernel"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/Libraries/PaperFrameBuffer"
    labels:
      - "Enhancement"
      - "Project:PaperFrameBuffer"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/Libraries/SulphurDioxide"
    labels:
      - "Enhancement"
      - "Project:SulphurDioxide"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/Extensions/FKTest"
    labels:
      - "Enhancement"
      - "Project:FKTest"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/Extensions/FKPCI"
    labels:
      - "Enhancement"
      - "Project:FKPCI"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/Extensions/AC97Audio"
    labels:
      - "Enhancement"
      - "Project:AC97Audio"
    schedule:
      interval: "daily"
