version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "Enhancement"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/Libraries/ACPI"
    labels:
      - "Enhancement"
      - "Project:ACPI"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/Libraries/AMD64"
    labels:
      - "Enhancement"
      - "Project:AMD64"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/BootX"
    labels:
      - "Enhancement"
      - "Project:BootX"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/Kernel"
    labels:
      - "Enhancement"
      - "Project:Kernel"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/Libraries/PaperFrameBuffer"
    labels:
      - "Enhancement"
      - "Project:PaperFrameBuffer"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/Libraries/SulphurDioxide"
    labels:
      - "Enhancement"
      - "Project:SulphurDioxide"
    schedule:
      interval: "daily"
