cargo-features = ["edition2021"]

[package]
name = "fuse"
version = "0.1.0"
authors = ["VisualDevelopment"]
publish = false
edition = "2021"

[profile.dev]
lto = "thin"

[profile.release]
lto = "thin"

[dependencies]
log = { version = "^0.4.14", default-features = false }
lazy_static = { version = "^1.4.0", features = ["spin_no_std"] }
spin = { version = "^0.9.2", default-features = false, features = ["lock_api", "mutex", "ticket_mutex", "use_ticket_mutex", "rwlock", "once", "lazy", "barrier"] }
elf_rs = "^0.1.3"
modular-bitfield = "^0.11.2"
bit = "^0.1.1"
bitflags = "^1.3.2"
volatile = "^0.4.4"
kaboom = { path = "../Kaboom" }