[package]
name = "fuse"
version = "0.1.0"
authors = ["VisualDevelopment"]
publish = false
edition = "2021"

[profile.dev]
lto = "thin"

[profile.release]
lto = "thin"

[dependencies]
log = { version = "0.4.14", default-features = false }
spin = { version = "0.9.2", default-features = false, features = [
    "lock_api",
    "mutex",
    "ticket_mutex",
    "use_ticket_mutex",
    "rwlock",
    "once",
    "barrier",
] }
xmas-elf = "0.8.0"
modular-bitfield = "0.11.2"
amd64 = { path = "../amd64" }
acpi = { path = "../acpi" }
kaboom = { path = "../kaboom" }
