[package]
name = "fuse"
description = "Firework kernel"
repository = "https://github.com/Firework-OS/Fuse"
publish = false
version = "0.1.0"
authors = ["VisualDevelopment"]
edition = "2021"
license-file = "LICENSE"

[profile.dev]
lto = "thin"

[profile.release]
lto = true

[dependencies]
log = { version = "0.4.14", default-features = false }
spin = { version = "0.9.2", default-features = false, features = [
    "lock_api",
    "mutex",
    "ticket_mutex",
    "use_ticket_mutex",
    "rwlock",
    "once",
    "barrier",
] }
font8x8 = { version = "0.3.1", default-features = false, features = [
    "unicode",
] }
modular-bitfield = "0.11.2"
amd64 = { path = "../AMD64" }
acpi = { path = "../ACPI" }
kaboom = { path = "../Kaboom" }
seq-macro = "0.3.0"
vesa = { path = "../VESA" }
