[workspace]
members = [
    "acpi",
    "amd64",
    "bootx",
    "cardboard",
    "cardboard-klib",
    "paper-fb",
    "sulphur-dioxide",
]
resolver = "2"

[profile.release]
lto = true
strip = true
