[package]
name = "fuse"
version = "0.1.0"
authors = ["VisualDevelopment"]
edition = "2021"
license-file = "LICENSE"

[profile.dev]
lto = "thin"

[profile.release]
lto = "thin"

[dependencies]
log = { version = "0.4.14", default-features = false }
spin = { version = "0.9.2", default-features = false, features = [
    "lock_api",
    "mutex",
    "ticket_mutex",
    "use_ticket_mutex",
    "rwlock",
    "once",
    "barrier",
] }
goblin = { version = "0.4.3", default-features = false, features = ["elf64"] }
modular-bitfield = "0.11.2"
amd64 = { path = "../AMD64" }
acpi = { path = "../ACPI" }
kaboom = { path = "../Kaboom" }
