[tasks.build-xboot]
args = ["--out-dir", "../Drive/EFI/BOOT", "build"]
command = "cargo"
cwd = "XBoot"

[tasks.build-kernel]
args = ["--out-dir", "../Drive/System", "build"]
command = "cargo"
cwd = "Kernel"

[tasks.build-xboot-release]
args = ["--out-dir", "--release", "../Drive/EFI/BOOT", "build"]
command = "cargo"
cwd = "XBoot"

[tasks.build-kernel-release]
args = ["--out-dir", "--release", "../Drive/System", "build"]
command = "cargo"
cwd = "Kernel"

[tasks.make-tkcache]
args = ["--release", "run"]
command = "cargo"
cwd = "Utilities/TKCacheBuilder"

[tasks.make-boot-exts]
args = ["make", "make"]
command = "cargo"
cwd = "Extensions"

[tasks.make-boot-exts-release]
args = ["make", "make-release"]
command = "cargo"
cwd = "Extensions"

[tasks.make]
dependencies = ["build-kernel", "build-xboot", "make-boot-exts", "make-tkcache"]

[tasks.make-release]
dependencies = [
    "build-kernel-release",
    "build-xboot-release",
    "make-boot-exts-release",
    "make-tkcache",
]

[tasks.run]
args = [
    "-M",
    "-audiodev",
    "-device",
    "-drive",
    "-drive",
    "-hda",
    "-m",
    "-serial",
    "1G",
    "ac97,audiodev=audio",
    "coreaudio,id=audio,out.frequency=48000",
    "fat:rw:Drive",
    "if=pflash,format=raw,readonly=on,unit=0,file=${@}/OVMF_CODE.fd",
    "if=pflash,format=raw,unit=1,file=${@}/OVMF_VARS.fd",
    "q35",
    "stdio",
]
command = "qemu-system-x86_64"
dependencies = ["make"]

[tasks.run-release]
args = [
    "-M",
    "-audiodev",
    "-device",
    "-drive",
    "-drive",
    "-hda",
    "-m",
    "1G",
    "ac97,audiodev=audio",
    "coreaudio,id=audio,out.frequency=48000",
    "fat:rw:Drive",
    "if=pflash,format=raw,readonly=on,unit=0,file=${@}/OVMF_CODE.fd",
    "if=pflash,format=raw,unit=1,file=${@}/OVMF_VARS.fd",
    "q35",
]
command = "qemu-system-x86_64"
dependencies = ["make-release"]

[config]
default_to_workspace = false
