[env]
CARGO_BUILD_PROFILE = "dev"

[env.production]
CARGO_BUILD_PROFILE = "release"

[tasks.build-skylift]
cwd = "SkyLift"
command = "cargo"
args = [
    "build",
    "--out-dir",
    "../Drive/EFI/BOOT",
    "--profile",
    "${CARGO_BUILD_PROFILE}",
]

[tasks.build-sky]
cwd = "Sky"
command = "cargo"
args = [
    "build",
    "--out-dir",
    "../Drive/System",
    "--profile",
    "${CARGO_BUILD_PROFILE}",
]

[tasks.make-skcache]
dependencies = ["make-boot-exts"]
cwd = "Utilities/SKCacheBuilder"
command = "cargo"
args = ["run", "--release"]

[tasks.make-boot-exts]
cwd = "Extensions"
command = "cargo"
args = ["make", "--profile", "${CARGO_MAKE_PROFILE}", "make"]

[tasks.make]
dependencies = ["build-skylift", "build-sky", "make-skcache"]

[tasks.run]
command = "qemu-system-x86_64"
args = [
    "-M",
    "q35",
    "-m",
    "1G",
    "-drive",
    "if=pflash,format=raw,readonly=on,unit=0,file=${@}/OVMF_CODE.fd",
    "-drive",
    "if=pflash,format=raw,unit=1,file=${@}/OVMF_VARS.fd",
    "-hda",
    "fat:rw:Drive",
    "-serial",
    "stdio",
    "-audiodev",
    "coreaudio,id=audio,out.frequency=48000",
    "-device",
    "ac97,audiodev=audio",
]
dependencies = ["make"]
