[env]
CARGO_MAKE_WORKSPACE_EMULATION = true
CARGO_MAKE_CRATE_WORKSPACE_MEMBERS = ["PCIKit", "SKTest"]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.make]
command = "cargo"
args = [
    "build",
    "--artifact-dir",
    "../../target/Extensions",
    "--profile",
    "${CARGO_MAKE_CARGO_PROFILE}",
]
