[tasks.make]
args = ["--out-dir", "../../target/Extensions", "build"]
command = "cargo"

[tasks.make-release]
args = ["--out-dir", "--release", "../../target/Extensions", "build"]
command = "cargo"

[config]
default_to_workspace = true

[env]
CARGO_MAKE_CRATE_WORKSPACE_MEMBERS = ["AC97Audio", "PCIKit", "TKTest"]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
CARGO_MAKE_WORKSPACE_EMULATION = true
