[env]
CARGO_BUILD_PROFILE = "dev"
CARGO_MAKE_WORKSPACE_EMULATION = true
CARGO_MAKE_CRATE_WORKSPACE_MEMBERS = ["PCIKit", "FKTest"]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[env.production]
CARGO_BUILD_PROFILE = "release"

[tasks.make]
command = "cargo"
args = [
    "build",
    "--out-dir",
    "../../target/Extensions",
    "--profile",
    "${CARGO_BUILD_PROFILE}",
]
