[tasks.make]
command = "cargo"
args = ["build", "--out-dir", "../../target/Extensions"]

[tasks.make-release]
command = "cargo"
args = ["build", "--out-dir", "../../target/Extensions", "--release"]

[config]
default_to_workspace = true

[env]
CARGO_MAKE_WORKSPACE_EMULATION = true
CARGO_MAKE_CRATE_WORKSPACE_MEMBERS = ["TKTest", "TKPCI"]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
