cargo-features = ["different-binary-name"]

[package]
edition = "2021"
name = "kernel"
publish = false
version = "0.1.0"

[[bin]]
name = "kernel"
filename = "Kernel"
required-features = ["bin"]

[dependencies]
acpi = { path = "../Libraries/ACPI", optional = true }
amd64 = { path = "../Libraries/AMD64", optional = true }
dc-cache = { path = "../Libraries/DCCache", optional = true, default-features = false }
font8x8 = { version = "0.3.1", optional = true, default-features = false }
goblin = { version = "0.6.0", optional = true, default-features = false, features = [
    "elf32",
    "elf64",
    "endian_fd",
] }
hashbrown = { version = "0.13.2", features = ["nightly", "serde"] }
log = { version = "0.4.17", optional = true, default-features = false, features = [
    "max_level_trace",
    "release_max_level_debug",
] }
modular-bitfield = { version = "0.11.2", git = "https://github.com/ChefKissInc/modular-bitfield", optional = true }
num_enum = { version = "0.5.7", default-features = false, features = [
    "nightly",
] }
paper-fb = { path = "../Libraries/PaperFrameBuffer", optional = true }
rustc-demangle = { version = "0.1.21", optional = true }
postcard = { version = "1.0.2", optional = true, default-features = false, features = [
    "alloc",
] }
seq-macro = { version = "0.3.2", optional = true }
spin = { version = "0.9.4", optional = true, default-features = false, features = [
    "barrier",
    "lock_api",
    "mutex",
    "once",
    "rwlock",
    "ticket_mutex",
    "use_ticket_mutex",
] }
sulphur-dioxide = { path = "../Libraries/SulphurDioxide", optional = true }
unwinding = { version = "0.1.5", optional = true, default-features = false, features = [
    "fde-static",
    "hide-trace",
    "panic",
    "personality",
    "unwinder",
] }
serde = { version = "1.0.152", default-features = false, features = ["derive"] }

[features]
default = ["bin"]
bin = [
    "acpi",
    "amd64",
    "dc-cache",
    "font8x8",
    "goblin",
    "log",
    "modular-bitfield",
    "paper-fb",
    "rustc-demangle",
    "postcard",
    "seq-macro",
    "spin",
    "sulphur-dioxide",
    "unwinding",
]
