cargo-features = ["different-binary-name"]

[package]
edition = "2021"
name = "kernel"
publish = false
version = "0.1.0"

[[bin]]
name = "kernel"
filename = "Kernel"

[dependencies]
amd64 = { path = "../Libraries/AMD64" }
tungstenkit = { path = "../Libraries/TungstenKit" }
goblin = { version = "0.6.1", default-features = false, features = [
    "elf32",
    "elf64",
    "endian_fd",
] }
hashbrown = { version = "0.13.2", features = ["nightly", "serde"] }
log = { version = "0.4.17", default-features = false, features = [
    "max_level_trace",
    "release_max_level_debug",
] }
modular-bitfield = { version = "0.11.2", git = "https://github.com/ChefKissInc/modular-bitfield" }
num_enum = { version = "0.6.0", default-features = false }
paper-fb = { path = "../Libraries/PaperFrameBuffer" }
rustc-demangle = "0.1.22"
postcard = { version = "1.0.4", default-features = false, features = ["alloc"] }
seq-macro = "0.3.3"
spin = { version = "0.9.8", default-features = false, features = [
    "barrier",
    "lock_api",
    "mutex",
    "once",
    "rwlock",
    "ticket_mutex",
    "use_ticket_mutex",
] }
sulphur-dioxide = { path = "../Libraries/SulphurDioxide" }
unwinding = { version = "0.1.6", default-features = false, features = [
    "fde-static",
    "hide-trace",
    "panic",
    "personality",
    "unwinder",
] }
serde = { version = "1.0.159", default-features = false, features = ["derive"] }
