[tasks.make]
command = "cargo"
args = [
    "build",
    "-Zbuild-std=core,compiler_builtins,alloc",
    "-Zbuild-std-features=compiler-builtins-mem",
    "--target",
    "../../x86_64-pc-bridgecore.json",
    "--out-dir",
    "../../target/DCExtensions",
]

[tasks.make-release]
command = "cargo"
args = [
    "build",
    "-Zbuild-std=core,compiler_builtins,alloc",
    "-Zbuild-std-features=compiler-builtins-mem",
    "--target",
    "../../x86_64-pc-bridgecore.json",
    "--out-dir",
    "../../target/DCExtensions",
    "--release",
]

[config]
default_to_workspace = true

[env]
CARGO_MAKE_WORKSPACE_EMULATION = true
CARGO_MAKE_CRATE_WORKSPACE_MEMBERS = ["PCICore"]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
