[package]
edition = "2021"
name = "amd64"
publish = false
version = "0.1.0"

[profile.release]
strip = true
lto = true

[dependencies]
arrayvec = { version = "0.7.4", default-features = false }
modular-bitfield = "0.11.2"
num_enum = { version = "0.6.1", default-features = false }
