[package]
edition = "2021"
name = "amd64"
publish = false
version = "0.1.0"

[profile.release]
strip = true

[dependencies]
arrayvec = { version = "0.7.4", default-features = false }
bitfield-struct = "0.9.0"
num_enum = { version = "0.7.2", default-features = false }
