name: Run cargo clippy and cargo test

on:
  push:
    branches: [master, staging, trying]
  pull_request:
    branches: [master]
  schedule:
    - cron: "19 2 * * 4"

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rust-src, rustfmt, clippy
      - name: Install cargo-make
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-make
          use-tool-cache: true
      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: fmt
          args: --all -- --check
      - name: Run lints
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: make
          args: clippy
  test:
    name: Test suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rust-src
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: test
          args: --workspace --exclude cardboard --exclude bootx
