name: Run lints and tests

on:
  push:
    branches: [master, staging, trying]
  pull_request:
    branches: [master]
  schedule:
    - cron: "19 2 * * 4"

env:
  CARGO_TERM_COLOR: always

jobs:
  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src, rustfmt, clippy
      - run: for f in $(find . -name "*Cargo.toml"); do cargo -Zunstable-options -C ${f%Cargo.toml} fmt --all -- --check || exit 1; done
      - run: for f in $(find . -name "*Cargo.toml"); do cargo -Zunstable-options -C ${f%Cargo.toml} clippy || exit 1; done
  test:
    name: Test suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src
      - run: for f in $(find . -name "*Cargo.toml" | egrep -v "^(./Kernel/|./XBoot/|./Extensions/PCIKit/|./Extensions/FKTest/|./Extensions/AC97Audio/)"); do cargo -Zunstable-options -C ${f%Cargo.toml} test || exit 1; done
